# Generated by Django 4.2.4 on 2023-08-06 07:46

from django.db import migrations, models
import phonenumber_field.modelfields
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_likes_number_like_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expiration_date',
            field=profiles.models.MonthYearField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_on_card',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
