# Generated by Django 4.2.4 on 2023-08-04 23:25

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_profile_type_alter_profile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('ton', 'ton'), ('9ontar', '9ontar'), ('meter', 'meter'), ('hour', 'hour'), ('day', 'day'), ('quantity', 'quantity')], max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unitcount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('selling_status', models.CharField(choices=[('big quantities only', 'big quantities only'), ('big and small quntities', 'big and small quntities')], max_length=50)),
                ('min_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('for_renting', 'for_renting'), ('for_selling', 'for_selling')], max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to=products.models.get_image_upload_path)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(blank=True, max_length=20, null=True, verbose_name='category name')),
                ('parent_cat', models.ForeignKey(blank=True, limit_choices_to={'parent_cat__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
