# Generated by Django 4.2.4 on 2023-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delevery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='delevery_range',
            field=models.CharField(choices=[('wilaya', 'wilaya'), ('baladiya', 'baladiya'), ('country', 'country'), ('no delevery', 'no delevery')], default='no delevry', max_length=50),
        ),
    ]
