# Generated by Django 4.2.4 on 2023-08-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_delevery_price_product_delevery_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='baladiya',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delevery_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delevery_range',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='payment_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wilaya',
        ),
    ]
