# Generated by Django 4.2.4 on 2023-08-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_baladiya_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
